import { IncidentPayload, IncidentCorrelation } from "@/types/incident-response";

export class IncidentReportService {
  /**
   * Generates a markdown report for the incident.
   * Can be used as a PR body or posted to Slack/Discord.
   */
  public generatePrDescription(
    incident: IncidentPayload,
    correlation: IncidentCorrelation
  ): string {
    return `
## GitVerse Incident Response

**Incident:** ${incident.title}
**Severity:** ${(incident.severity ?? "medium").toUpperCase()}
**Likely Source:** PR #${correlation.likelyPrNumber || "Unknown"}
**Confidence:** ${correlation.confidenceScore}%

### Incident Summary
A critical production incident was detected via ${incident.source}. 
The automated correlation engine analyzed recent deployments and determined that PR #${correlation.likelyPrNumber} is the most likely root cause.

### Root Cause Analysis
${correlation.analysisDetails}

### Affected Components
- **Services:** ${correlation.impactedServices.join(", ") || incident.affectedService || "None specified"}
- **Files:** ${correlation.impactedFiles.join(", ") || "None specified"}

### Auto-Rollback Status
**Rollback Prepared:** Yes
**Emergency PR:** Created

---
*This PR was automatically generated by GitVerse's Automated Incident Response Pipeline.*
    `.trim();
  }
}

let incidentReportSingleton: IncidentReportService | null = null;

export function getIncidentReportService(): IncidentReportService {
  if (!incidentReportSingleton) {
    incidentReportSingleton = new IncidentReportService();
  }
  return incidentReportSingleton;
}
