import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { GitHubService } from '@/lib/services/githubService';
import { getDecryptedGitHubToken } from '@/lib/utils/githubToken';
import { secretDetector } from '@/lib/services/secret-detector';
import { RiskScorer } from '@/lib/services/riskScorer';
import { DependencyGraphAnalyzer } from '@/lib/services/dependencyGraphAnalyzer';
import { getGeminiService } from '@/lib/services/geminiService';
import { isCronAuthorized } from '@/lib/utils/internalAuth';

export async function GET(req: Request) {
  if (!isCronAuthorized(req.headers.get('authorization'))) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const repos = await prisma.repository.findMany({ include: { user: true } });

    for (const repo of repos) {
      if (!repo.url) continue;

      const token = await getDecryptedGitHubToken(repo.userId);
      const githubService = new GitHubService(token || undefined);
      const geminiService = getGeminiService();

      const match = repo.url.match(/github\.com\/([^\/]+)\/([^\/]+)/);
      if (!match) continue;
      const [, owner, repoName] = match;

      const commits = await githubService.getCommits(owner, repoName, { per_page: 5 }).catch(() => []);
      const changedFiles = new Set<string>();
      let techDebtNotes = 'No recent changes detected.';
      let secretRisks = 0;
      let riskResult = { level: 'LOW', score: 0, factors: [] as string[] };

      if (commits.length > 0) {
        const latestCommit = await githubService.getCommit(owner, repoName, commits[0].sha).catch(() => null);
        const files = (latestCommit as any)?.files || [];
        files.forEach((f: any) => changedFiles.add(f.filename));

        const impact = await DependencyGraphAnalyzer.analyzeImpact(repo.url, Array.from(changedFiles)).catch(() => ({ affectedFiles: [], dependencyPaths: {}, downstreamCount: 0 }));
        riskResult = RiskScorer.calculateRisk(Array.from(changedFiles), impact as any, []);

        for (const file of files.slice(0, 3)) {
           if (file.patch) {
               const secrets = await secretDetector.scanFile(file.filename, file.patch);
               if (secrets.length > 0) secretRisks += secrets.length;
           }
        }

        if (changedFiles.size > 0) {
            const prompt = `Analyze these recent changed files for growing technical debt and unused code:\n\nFiles: ${Array.from(changedFiles).join(', ')}`;
            const aiResponse = await geminiService.chatRaw(prompt).catch(() => ({ text: 'Could not analyze technical debt.' }));
            techDebtNotes = aiResponse.text;
        }
      }

      const digestBody = `## Weekly Health Digest\n\n### Technical Debt & Unused Code\n${techDebtNotes}\n\n### Security & Secret Risks\n- Detected Secrets: ${secretRisks}\n- Risk Level: ${riskResult.level} (Score: ${riskResult.score})\n- Factors:\n${riskResult.factors.map(f => `  - ${f}`).join('\n')}\n\nThis is an automated digest generated by GitVerse.`;

      try {
        await githubService.createIssue(owner, repoName, `Weekly Health Digest - ${new Date().toISOString().split('T')[0]}`, digestBody);
      } catch (e) { console.warn('Failed to create github issue', e); }
    }

    return NextResponse.json({ success: true, processedCount: repos.length });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
